/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import connect.ConnectSV;
import java.text.MessageFormat;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author TranThuyNga
 */
public class QLyHSSV_form extends javax.swing.JFrame {
    ConnectSV Sv=new ConnectSV();
    /**
     * Creates new form QLyHSSV_form
     */
    public QLyHSSV_form() {
        new DangNhapForm().setVisible(true);
    }
    public QLyHSSV_form(String s) {
        initComponents();
        setLocationRelativeTo(null);
        loadDataSV();
        ButtonGroup gr=new ButtonGroup();
        gr.add(rdnam);
        gr.add(rdnu);
        setTitle("Phần mềm quản lý Sinh Viên");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        center = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jpnSinhVien = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SVtxtmasv = new javax.swing.JTextField();
        SVtxtmalop = new javax.swing.JTextField();
        SVtxthoten = new javax.swing.JTextField();
        Svtxtqq = new javax.swing.JTextField();
        SVtxtqt = new javax.swing.JTextField();
        SVtxtCmtnd = new javax.swing.JTextField();
        SVtxtns = new javax.swing.JTextField();
        rdnam = new javax.swing.JCheckBox();
        rdnu = new javax.swing.JCheckBox();
        btnXoaTrang = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableSinhVien = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnThemsv = new javax.swing.JButton();
        btnSuaSv = new javax.swing.JButton();
        btnXoasv = new javax.swing.JButton();
        btnSapSV = new javax.swing.JButton();
        btnloadsv = new javax.swing.JButton();
        btnThoatsv = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        SVtxtTimKiemlop = new javax.swing.JTextField();
        btnXemSvTL = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txttimkiemsv = new javax.swing.JTextField();
        btntim = new javax.swing.JButton();
        btnin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        diem = new javax.swing.JMenu();

        center.setPreferredSize(new java.awt.Dimension(1250, 600));
        center.setLayout(new java.awt.CardLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("PHẦN MỀM QUẢN LÝ SINH VIÊN");

        jpnSinhVien.setPreferredSize(new java.awt.Dimension(1250, 500));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập dữ liệu"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã Sinh viên:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã lớp:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giới tính:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Quê quán:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quốc tịch:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CMTND");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Ngày sinh:");

        SVtxtmasv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SVtxtmalop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SVtxthoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SVtxthoten.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        Svtxtqq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SVtxtqt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SVtxtCmtnd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        SVtxtns.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rdnam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdnam.setSelected(true);
        rdnam.setText("Nam");

        rdnu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdnu.setText("Nữ");

        btnXoaTrang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdnam, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdnu, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addComponent(SVtxtmasv, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SVtxtmalop, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SVtxthoten, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Svtxtqq)
                    .addComponent(SVtxtqt)
                    .addComponent(SVtxtCmtnd)
                    .addComponent(SVtxtns))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoaTrang)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(SVtxtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SVtxtmalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SVtxthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnu)
                    .addComponent(rdnam)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Svtxtqq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SVtxtqt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SVtxtCmtnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SVtxtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaTrang)
                .addGap(12, 12, 12))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách"));
        jPanel3.setPreferredSize(new java.awt.Dimension(550, 211));

        jtableSinhVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtableSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableSinhVien.setPreferredSize(new java.awt.Dimension(450, 600));
        jtableSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableSinhVien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn"));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        btnThemsv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThemsv.setText("Thêm");
        btnThemsv.setPreferredSize(new java.awt.Dimension(63, 31));
        btnThemsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemsvActionPerformed(evt);
            }
        });
        jPanel6.add(btnThemsv);

        btnSuaSv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSuaSv.setText("Sửa");
        btnSuaSv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSvActionPerformed(evt);
            }
        });
        jPanel6.add(btnSuaSv);

        btnXoasv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoasv.setText("Xóa ");
        btnXoasv.setPreferredSize(new java.awt.Dimension(63, 31));
        btnXoasv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoasvActionPerformed(evt);
            }
        });
        jPanel6.add(btnXoasv);

        btnSapSV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSapSV.setText("Sắp");
        btnSapSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapSVActionPerformed(evt);
            }
        });
        jPanel6.add(btnSapSV);

        btnloadsv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnloadsv.setText("Load");
        btnloadsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadsvActionPerformed(evt);
            }
        });
        jPanel6.add(btnloadsv);

        btnThoatsv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoatsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-1.png"))); // NOI18N
        btnThoatsv.setText("Quay lại");
        btnThoatsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatsvActionPerformed(evt);
            }
        });
        jPanel6.add(btnThoatsv);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("QUẢN LÝ HỒ SƠ SINH VIÊN");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("MaLop");

        SVtxtTimKiemlop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnXemSvTL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXemSvTL.setText("Xem Sinh Viên Theo Lớp");
        btnXemSvTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemSvTLActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("MaSV:");

        txttimkiemsv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btntim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntim.setText("Tìm kiếm sinh viên");
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });

        btnin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnin.setText("In Danh Sách");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(SVtxtTimKiemlop, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txttimkiemsv, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXemSvTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnin)
                .addGap(117, 117, 117))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(SVtxtTimKiemlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXemSvTL)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnin)))
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txttimkiemsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnSinhVienLayout = new javax.swing.GroupLayout(jpnSinhVien);
        jpnSinhVien.setLayout(jpnSinhVienLayout);
        jpnSinhVienLayout.setHorizontalGroup(
            jpnSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSinhVienLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jpnSinhVienLayout.setVerticalGroup(
            jpnSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSinhVienLayout.createSequentialGroup()
                .addGroup(jpnSinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnSinhVienLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemActionPerformed(evt);
            }
        });
        jMenuBar1.add(diem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jpnSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 1222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jpnSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDataSV(){
        Sv.getConnect();
        Vector<Vector<String>> data;
    try {
        data = Sv.GetData("SINHVIEN");
        Vector<String> header = new Vector<String>();
                header.add("Mã Sinh viên");
                header.add("mã lớp");
                header.add("Họ Tên");
                header.add("Giới Tính");
                header.add("Quê Quán");
                header.add("Quốc tịch");
                header.add("Cmtnd");
                header.add("Ngày Sinh");
        ((DefaultTableModel) (jtableSinhVien.getModel())).setDataVector(data, header);
        jtableSinhVien.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtableSinhVien.getColumnModel().getColumn(3).setPreferredWidth(50);
         } catch (SQLException ex) {
        Logger.getLogger(QLyHSSV_form.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    int vtri;
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int ref=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thoát","Thoát",JOptionPane.YES_NO_OPTION);
        if(ref==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void diemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diemActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        clearTextSv();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void jtableSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableSinhVienMouseClicked
        vtri=evt.getClickCount();
        if(vtri>=0)
        {
            SVtxtmasv.setText(jtableSinhVien.getValueAt(jtableSinhVien.getSelectedRow(), 0).toString());
            SVtxtmalop.setText(jtableSinhVien.getValueAt(jtableSinhVien.getSelectedRow(), 1).toString());
            SVtxthoten.setText(jtableSinhVien.getValueAt(jtableSinhVien.getSelectedRow(), 2).toString());
            Svtxtqq.setText(jtableSinhVien.getValueAt(jtableSinhVien.getSelectedRow(), 4).toString());
            SVtxtqt.setText(jtableSinhVien.getValueAt(jtableSinhVien.getSelectedRow(), 5).toString());
            SVtxtns.setText(jtableSinhVien.getValueAt(jtableSinhVien.getSelectedRow(), 7).toString());
            SVtxtCmtnd.setText(jtableSinhVien.getValueAt(jtableSinhVien.getSelectedRow(), 6).toString());
            if(jtableSinhVien.getValueAt(jtableSinhVien.getSelectedRow(), 3).toString().equals("Nam")){
                rdnam.setSelected(true);
            }
            else{
                rdnu.setSelected(true);}
        }
    }//GEN-LAST:event_jtableSinhVienMouseClicked

    private void btnThemsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemsvActionPerformed
        Sv.getConnect();
        if(SVtxtmasv.getText().isEmpty()||SVtxtmalop.getText().isEmpty() || Svtxtqq.getText().isEmpty()|| SVtxtqt.getText().isEmpty()
            || SVtxtns.getText().isEmpty()||SVtxthoten.getText().isEmpty()|| SVtxtCmtnd.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Thêm thất bại. Không được để trống.");
        }
        else if(Sv.checkMaSV(SVtxtmasv.getText())){
            JOptionPane.showMessageDialog(null, "Mã sinh viên đã tồn tại.");
            SVtxtmasv.requestFocus();
        }
        else if(Sv.checkCmtnd(SVtxtCmtnd.getText())){
            JOptionPane.showMessageDialog(null, "CMTND đã tồn tại");
            SVtxtCmtnd.requestFocus();
        }
        else if(!Pattern.matches("[S][V]\\d{4}", SVtxtmasv.getText())) {JOptionPane.showMessageDialog(null, "Thêm thất bại. Mã SV cần bắt đầu bằng SV theo sau là 4 số.");
            SVtxtmasv.requestFocus();
        }
        else if(!Pattern.matches("[0-9]{10,10}", SVtxtCmtnd.getText())) {
            JOptionPane.showMessageDialog(null, "Thêm thất bại. Cmtnd phải là 10 chữ số.");
            SVtxtCmtnd.requestFocus();
        }
        else if(!Pattern.matches("^\\d{4}[-]\\d{2}[-]\\d{2}$", SVtxtns.getText())) {
            JOptionPane.showMessageDialog(null, "Thêm thất bại. Ngày sinh phải có định dạng năm-tháng-ngày.");
            SVtxtns.requestFocus();
        }
        else if(!Sv.checkMaLop(SVtxtmalop.getText())){ JOptionPane.showMessageDialog(null, "Thêm thất bại. Không tồn tại mã lớp");
            SVtxtmalop.requestFocus();
        }
        else{
            String gt;
            if(rdnam.isSelected()){
                gt=rdnam.getText();
            }
            else
            gt=rdnu.getText();
            if(Sv.add(SVtxtmasv.getText(), SVtxtmalop.getText(), SVtxthoten.getText(), gt, Svtxtqq.getText(),
                SVtxtqt.getText(), SVtxtns.getText(), SVtxtCmtnd.getText())>0){
                JOptionPane.showMessageDialog(null, "Thêm Thành công");
            }else{
                JOptionPane.showMessageDialog(null, "Thêm thất bại: Sai định dạng ngàyl");
            }
            loadDataSV();
            clearTextSv();
            try {
                Sv.closeConnect();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Không đóng được csdl");
            }
        }
    }//GEN-LAST:event_btnThemsvActionPerformed

    private void btnSuaSvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSvActionPerformed
        Sv.getConnect();
        if(SVtxtmasv.getText().isEmpty()||SVtxtmalop.getText().isEmpty() || Svtxtqq.getText().isEmpty()|| SVtxtqt.getText().isEmpty()
            || SVtxtns.getText().isEmpty()||SVtxthoten.getText().isEmpty()|| SVtxtCmtnd.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Sửa thất bại");
        }
        else if(!Sv.checkMaSV(SVtxtmasv.getText())){
            JOptionPane.showMessageDialog(null, "Không tồn tại maSv: "+ SVtxtmasv.getText());
        }
        else if(Sv.checkCmtnd(SVtxtCmtnd.getText(), SVtxtmasv.getText())){
            JOptionPane.showMessageDialog(null, "CMTND đã tồn tại");
            SVtxtCmtnd.requestFocus();
        }
        else if(!Pattern.matches("[0-9]{10,10}", SVtxtCmtnd.getText())) JOptionPane.showMessageDialog(null, "Sửa thất bại. Cmtnd phải là 10 chữ số..");
        else if(!Pattern.matches("^\\d{4}[-]\\d{2}[-]\\d{2}$", SVtxtns.getText())) JOptionPane.showMessageDialog(null, "Sửa thất bại. Ngày sinh phải có định dạng năm-tháng-ngày.");
        else if(!Sv.checkMaLop(SVtxtmalop.getText())) JOptionPane.showMessageDialog(null, "Sửa thất bại. Không tồn tại mã lớp");
        else{
            String gt;
            if(rdnam.isSelected()){
                gt=rdnam.getText();
            }
            else
            gt=rdnu.getText();
            if(Sv.update(SVtxtmasv.getText(), SVtxtmalop.getText(), SVtxthoten.getText(), gt, Svtxtqq.getText(),
                    SVtxtqt.getText(), SVtxtns.getText(), SVtxtCmtnd.getText())>0){
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
           }else{
                     JOptionPane.showMessageDialog(null, "Sửa thất bại");
                }
            loadDataSV();
            clearTextSv();
            try {
                Sv.closeConnect();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Không đóng được csdl");
            }
        }
    }//GEN-LAST:event_btnSuaSvActionPerformed

    private void btnXoasvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoasvActionPerformed
        Sv.getConnect();
        if(SVtxtmasv.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Không được để trống masv");
        }else{
        try {
            if(!Sv.checkMaSV(SVtxtmasv.getText())){
                JOptionPane.showMessageDialog(null, "Không tồn tại maSv: "+ SVtxtmasv.getText());
            }
            else if(Sv.checkMaSVDiem(SVtxtmasv.getText())) 
                JOptionPane.showMessageDialog(null, "Sinh viên "+ SVtxtmasv.getText()+" đã có điếm không xóa được");
            else{
                int ref=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa sv "+SVtxtmasv.getText(),"Xóa",JOptionPane.YES_NO_OPTION );
                if(ref==JOptionPane.YES_OPTION){
                    if(Sv.remove(SVtxtmasv.getText())>0)
                    JOptionPane.showMessageDialog(null, "Xóa Thành công");
                    else{
                         JOptionPane.showMessageDialog(null, "Xóa thất bại");
                    }
                }
            }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
            }
        }
            clearTextSv();
            loadDataSV();
            try {
                Sv.closeConnect();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Không đóng được csdl");
            }
            
    }//GEN-LAST:event_btnXoasvActionPerformed

    private void btnSapSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapSVActionPerformed
        Sv.getConnect();
        Vector<Vector<String>> data;
    try {
        data = Sv.Sap();
        Vector<String> header = new Vector<String>();
			header.add("Mã Sinh viên");
			header.add("mã lớp");
			header.add("Họ Tên");
			header.add("Giới Tính");
			header.add("Quê Quán");
			header.add("Quốc tịch");
			header.add("Cmtnd");
			header.add("Ngày Sinh");
        ((DefaultTableModel) (jtableSinhVien.getModel())).setDataVector(data, header);
        jtableSinhVien.getColumnModel().getColumn(2).setPreferredWidth(150);
        jtableSinhVien.getColumnModel().getColumn(3).setPreferredWidth(50);
         } catch (SQLException ex) {
        Logger.getLogger(QLyHSSV_form.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnSapSVActionPerformed

    private void btnloadsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadsvActionPerformed
        loadDataSV();
    }//GEN-LAST:event_btnloadsvActionPerformed

    private void btnThoatsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatsvActionPerformed
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        new QLSV_FORM("chay").setVisible(true);
    }//GEN-LAST:event_btnThoatsvActionPerformed

    private void btnXemSvTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemSvTLActionPerformed
        if(SVtxtTimKiemlop.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Không được để trống ");
        }
        else{
            Sv.getConnect();
            Vector<Vector<String>> data;
            try {
                data =Sv.findLop(SVtxtTimKiemlop.getText());
                Vector<String> header = new Vector<String>();
                    header.add("Mã Sinh viên");
                    header.add("mã lớp");
                    header.add("Họ Tên");
                    header.add("Giới Tính");
                    header.add("Quê Quán");
                    header.add("Quốc tịch");
                    header.add("Cmtnd");
                    header.add("Ngày Sinh");
                 if(data.size()==0){
                   JOptionPane.showMessageDialog(null, "Không tồn tại lop: "+SVtxtTimKiemlop.getText());
                 }else{
                    JOptionPane.showMessageDialog(null, "Có " +data.size()+" Sinh Viên trong lớp "+SVtxtTimKiemlop.getText());
                 }
                SVtxtTimKiemlop.setText("");
                SVtxtTimKiemlop.requestFocus();
               ((DefaultTableModel) (jtableSinhVien.getModel())).setDataVector(data, header);
                jtableSinhVien.getColumnModel().getColumn(2).setPreferredWidth(150);
                jtableSinhVien.getColumnModel().getColumn(3).setPreferredWidth(50); 
            } catch (Exception ex) {
                Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXemSvTLActionPerformed

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        if(txttimkiemsv.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Không được để trống ");
        }
        else{
            Sv.getConnect();
            Vector<Vector<String>> data;
            try {
                data = Sv.findMasv(txttimkiemsv.getText());
                Vector<String> header = new Vector<String>();
                    header.add("Mã Sinh viên");
                    header.add("mã lớp");
                    header.add("Họ Tên");
                    header.add("Giới Tính");
                    header.add("Quê Quán");
                    header.add("Quốc tịch");
                    header.add("Cmtnd");
                    header.add("Ngày Sinh");
                 if(!Sv.checkMaSV(txttimkiemsv.getText())){
                     JOptionPane.showMessageDialog(null, "Không có Sinh Viên mã: "+txttimkiemsv.getText());
                 }else{
                    JOptionPane.showMessageDialog(null, "Có " +data.size()+" Sinh Viên mã: "+txttimkiemsv.getText());
                 }
                txttimkiemsv.setText("");
                txttimkiemsv.requestFocus();
               ((DefaultTableModel) (jtableSinhVien.getModel())).setDataVector(data, header);
                jtableSinhVien.getColumnModel().getColumn(2).setPreferredWidth(150);
                jtableSinhVien.getColumnModel().getColumn(3).setPreferredWidth(50); 
            } catch (Exception ex) {
                Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btntimActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed

     if(jtableSinhVien.getRowCount()<=0){
            JOptionPane.showMessageDialog(null, "Không in được: dữ liệu trống.");
        }else{
    try {
        MessageFormat header = new MessageFormat("Danh sách Sinh Viên");
        MessageFormat footer = new MessageFormat("HẾT");
        jtableSinhVien.print(JTable.PrintMode.FIT_WIDTH, header, footer);
    } catch (Exception e1) {
        JOptionPane.showMessageDialog(null, "Print failure\nDetails: " + e1);
    }
        }

    }//GEN-LAST:event_btninActionPerformed
private void clearTextSv(){
    SVtxtCmtnd.setText("");
    SVtxthoten.setText("");
    Svtxtqq.setText("");
    SVtxtqt.setText("");
    SVtxtns.setText("");
    SVtxtmasv.setText("");
    SVtxtmalop.setText("");
    SVtxtmasv.requestFocus();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLyHSSV_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLyHSSV_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLyHSSV_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLyHSSV_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLyHSSV_form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SVtxtCmtnd;
    private javax.swing.JTextField SVtxtTimKiemlop;
    private javax.swing.JTextField SVtxthoten;
    private javax.swing.JTextField SVtxtmalop;
    private javax.swing.JTextField SVtxtmasv;
    private javax.swing.JTextField SVtxtns;
    private javax.swing.JTextField SVtxtqt;
    private javax.swing.JTextField Svtxtqq;
    private javax.swing.JButton btnSapSV;
    private javax.swing.JButton btnSuaSv;
    private javax.swing.JButton btnThemsv;
    private javax.swing.JButton btnThoatsv;
    private javax.swing.JButton btnXemSvTL;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JButton btnXoasv;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnloadsv;
    private javax.swing.JButton btntim;
    private javax.swing.JPanel center;
    private javax.swing.JMenu diem;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnSinhVien;
    private javax.swing.JTable jtableSinhVien;
    private javax.swing.JCheckBox rdnam;
    private javax.swing.JCheckBox rdnu;
    private javax.swing.JTextField txttimkiemsv;
    // End of variables declaration//GEN-END:variables
}
