/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connect.ConnectKQHT;
import connect.ConnectSV;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QLyKQHT_form extends javax.swing.JFrame {
public static ResultSet rs=null;
    public Statement st;
    Connection conn = null;
    ConnectSV Sv=new ConnectSV();
     ConnectKQHT Ht=new ConnectKQHT();
    /**
     * Creates new form QLyKQHT_form
     */
    public QLyKQHT_form() {
        new DangNhapForm().setVisible(true);
    }
public QLyKQHT_form(String d) {
        initComponents();
        setLocationRelativeTo(null);
        loadKetQuaHocTap();
        setTitle("Phần mềm quản lý Sinh Viên");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jpnDiem = new javax.swing.JPanel();
        jPanelNhapDL = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtxtMaMon = new javax.swing.JTextField();
        jtxtMaSV = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtDiemTP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtDiemThi = new javax.swing.JTextField();
        jPanelDS = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableQLKQHT = new javax.swing.JTable();
        jPanelChon = new javax.swing.JPanel();
        jbtnThemDiem = new javax.swing.JButton();
        jbtnSuaDiem = new javax.swing.JButton();
        jbtnXoaDiem = new javax.swing.JButton();
        jbtnSapDiem = new javax.swing.JButton();
        jbtnLoadDiem = new javax.swing.JButton();
        jbtnThoatDiem = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jtxtTimMaSV = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jtxtTimMaMon = new javax.swing.JTextField();
        timkiemDiem = new javax.swing.JButton();
        tbnTimKiembySv = new javax.swing.JButton();
        btnTimKiembyMH = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PHẦN MỀM QUẢN LÝ SINH VIÊN");

        jpnDiem.setPreferredSize(new java.awt.Dimension(1200, 500));

        jPanelNhapDL.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập dữ liệu"));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Mã SV");

        jtxtMaMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtxtMaSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mã Môn");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Điểm thành phần");

        jtxtDiemTP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Điểm thi");

        jtxtDiemThi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelNhapDLLayout = new javax.swing.GroupLayout(jPanelNhapDL);
        jPanelNhapDL.setLayout(jPanelNhapDLLayout);
        jPanelNhapDLLayout.setHorizontalGroup(
            jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhapDLLayout.createSequentialGroup()
                .addGroup(jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNhapDLLayout.createSequentialGroup()
                        .addGroup(jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNhapDLLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtMaMon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDiemTP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelNhapDLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNhapDLLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNhapDLLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jtxtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addContainerGap())
        );
        jPanelNhapDLLayout.setVerticalGroup(
            jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhapDLLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(56, 56, 56)
                .addGroup(jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(65, 65, 65)
                .addGroup(jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtDiemTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanelNhapDLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtDiemThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        jPanelDS.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách"));

        jTableQLKQHT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableQLKQHT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableQLKQHT.setPreferredSize(new java.awt.Dimension(400, 400));
        jTableQLKQHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQLKQHTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableQLKQHT);

        javax.swing.GroupLayout jPanelDSLayout = new javax.swing.GroupLayout(jPanelDS);
        jPanelDS.setLayout(jPanelDSLayout);
        jPanelDSLayout.setHorizontalGroup(
            jPanelDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelDSLayout.setVerticalGroup(
            jPanelDSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDSLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanelChon.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn"));
        jPanelChon.setLayout(new java.awt.GridLayout(1, 0));

        jbtnThemDiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnThemDiem.setText("Thêm");
        jbtnThemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemDiemActionPerformed(evt);
            }
        });
        jPanelChon.add(jbtnThemDiem);

        jbtnSuaDiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSuaDiem.setText("Sửa");
        jbtnSuaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaDiemActionPerformed(evt);
            }
        });
        jPanelChon.add(jbtnSuaDiem);

        jbtnXoaDiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnXoaDiem.setText("Xoá");
        jbtnXoaDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaDiemActionPerformed(evt);
            }
        });
        jPanelChon.add(jbtnXoaDiem);

        jbtnSapDiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSapDiem.setText("Sắp");
        jbtnSapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSapDiemActionPerformed(evt);
            }
        });
        jPanelChon.add(jbtnSapDiem);

        jbtnLoadDiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnLoadDiem.setText("Load");
        jbtnLoadDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoadDiemActionPerformed(evt);
            }
        });
        jPanelChon.add(jbtnLoadDiem);

        jbtnThoatDiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnThoatDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-1.png"))); // NOI18N
        jbtnThoatDiem.setText("Quay lại");
        jbtnThoatDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThoatDiemActionPerformed(evt);
            }
        });
        jPanelChon.add(jbtnThoatDiem);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("QUẢN LÝ KẾT QUẢ HỌC TẬP");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("MaSV");

        jtxtTimMaSV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("MaMon");

        jtxtTimMaMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        timkiemDiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timkiemDiem.setText("Tìm kiếm Theo SV,MH");
        timkiemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemDiemActionPerformed(evt);
            }
        });

        tbnTimKiembySv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbnTimKiembySv.setText("Tìm kiếm Theo SV");
        tbnTimKiembySv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnTimKiembySvActionPerformed(evt);
            }
        });

        btnTimKiembyMH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimKiembyMH.setText("Tìm kiếm Theo MH");
        btnTimKiembyMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiembyMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtTimMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtTimMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(timkiemDiem)
                        .addGap(28, 28, 28)
                        .addComponent(tbnTimKiembySv, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiembyMH, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtTimMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timkiemDiem)
                            .addComponent(tbnTimKiembySv)
                            .addComponent(btnTimKiembyMH))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTimMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jpnDiemLayout = new javax.swing.GroupLayout(jpnDiem);
        jpnDiem.setLayout(jpnDiemLayout);
        jpnDiemLayout.setHorizontalGroup(
            jpnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnDiemLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanelNhapDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelChon, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        jpnDiemLayout.setVerticalGroup(
            jpnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDiemLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDiemLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelNhapDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jpnDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int ref=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thoát","Thoát",JOptionPane.YES_NO_OPTION);
        if(ref==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTableQLKQHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQLKQHTMouseClicked
        viTri = evt.getClickCount();
        if(viTri>=0)
        {
            jtxtMaSV.setText(jTableQLKQHT.getValueAt(jTableQLKQHT.getSelectedRow(), 0).toString());
            jtxtMaMon.setText(jTableQLKQHT.getValueAt(jTableQLKQHT.getSelectedRow(), 1).toString());
            jtxtDiemTP.setText(jTableQLKQHT.getValueAt(jTableQLKQHT.getSelectedRow(), 2).toString());
            jtxtDiemThi.setText(jTableQLKQHT.getValueAt(jTableQLKQHT.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_jTableQLKQHTMouseClicked

    private void jbtnThemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemDiemActionPerformed
        Sv.getConnect();
        if(jtxtMaSV.getText().isEmpty()|| jtxtMaMon.getText().isEmpty()|| jtxtDiemTP.getText().isEmpty()||jtxtDiemThi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Không được để trống");
        }
        else{
            Ht.getConnect();
            try {
                double diemTB = Double.parseDouble(jtxtDiemTP.getText())*0.3  + Double.parseDouble(jtxtDiemThi.getText())*0.7;
                if(!Ht.checkMaMh(jtxtMaMon.getText())) JOptionPane.showMessageDialog(null, "Không tồn tại mã môn học");
                else if(!Sv.checkMaSV(jtxtMaSV.getText()))  JOptionPane.showMessageDialog(null, "Không tồn tại mã sinh viên ");
                else if(Ht.checkMaSVMaMon(jtxtMaSV.getText(), jtxtMaMon.getText())){
                    JOptionPane.showMessageDialog(null, "Đã tồn tại mã sinh viên và mã môn");
                }
                else if(Double.parseDouble(jtxtDiemTP.getText())<0 || Double.parseDouble(jtxtDiemThi.getText())<0){
                    JOptionPane.showMessageDialog(null, "Điểm không được dưới 0");
                }
                else if(Double.parseDouble(jtxtDiemTP.getText())>10 || Double.parseDouble(jtxtDiemThi.getText())>10){
                    JOptionPane.showMessageDialog(null, "Điểm không được trên 10");
                }
                else{
                    double diem4=thangDiem4(diemTB);
                    String diemChu=thangDiemChu(diemTB);
                    String xepLoai=xepLoai(diemTB);
                    Ht.add(jtxtMaSV.getText(), jtxtMaMon.getText(), Double.parseDouble(jtxtDiemTP.getText()), Double.parseDouble(jtxtDiemThi.getText()), diemTB,diem4,diemChu,xepLoai);
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
                Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
            }
            loadKetQuaHocTap();
            try {
                Ht.closeConnect();
            } catch (SQLException e) {
                Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        xoaTrangDiem();
    }//GEN-LAST:event_jbtnThemDiemActionPerformed

    private void jbtnSuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaDiemActionPerformed
        if (jtxtMaSV.getText().isEmpty()|| jtxtMaMon.getText().isEmpty()|| jtxtDiemTP.getText().isEmpty()||jtxtDiemThi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Không được để trống");
        }
        else{
            Ht.getConnect();
            try {
                if  (!Ht.checkMaSVMaMon(jtxtMaSV.getText(), jtxtMaMon.getText())){
                    JOptionPane.showMessageDialog(null, "Không tồn tại mã sinh viên và mã môn");
                }
                else if(Double.parseDouble(jtxtDiemTP.getText())<0 || Double.parseDouble(jtxtDiemThi.getText())<0){
                    JOptionPane.showMessageDialog(null, "Điểm không được dưới 0");
                }
                else if(Double.parseDouble(jtxtDiemTP.getText())>10 || Double.parseDouble(jtxtDiemThi.getText())>10){
                    JOptionPane.showMessageDialog(null, "Điểm không được trên 10");
                }
                else{
                    double diemTB = Double.parseDouble(jtxtDiemTP.getText())*0.3  + Double.parseDouble(jtxtDiemThi.getText())*0.7;
                    double diem4=thangDiem4(diemTB);
                    String diemChu=thangDiemChu(diemTB);
                    String xepLoai=xepLoai(diemTB);
                    Ht.update(jtxtMaSV.getText(), jtxtMaMon.getText(), Double.parseDouble(jtxtDiemTP.getText()),
                        Double.parseDouble(jtxtDiemThi.getText()), diemTB,diem4,diemChu,xepLoai);
                    JOptionPane.showMessageDialog(null, "Sửa thành công");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
                Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
            }
            loadKetQuaHocTap();
            try {
                Ht.closeConnect();
            } catch (Exception e) {
                Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
            }
            try {
                Ht.closeConnect();
            } catch (SQLException e) {
                Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        xoaTrangDiem();
    }//GEN-LAST:event_jbtnSuaDiemActionPerformed

    private void jbtnXoaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaDiemActionPerformed
        Ht.getConnect();
        try {
            if(!Ht.checkMaSVMaMon(jtxtMaSV.getText(), jtxtMaMon.getText())){
                JOptionPane.showMessageDialog(null, "Không tồn tại mã sinh viên và mã môn");
            }
            else{
                Ht.remove(jtxtMaSV.getText(), jtxtMaMon.getText());
                JOptionPane.showMessageDialog(null, "Xoá thành công");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xoá thất bại");
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
        }
        xoaTrangDiem();
        loadKetQuaHocTap();
        try {
            Ht.closeConnect();
        } catch (Exception e) {
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null,e);
        }
        try {
            Ht.closeConnect();
        } catch (SQLException e) {
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jbtnXoaDiemActionPerformed

    private void jbtnSapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSapDiemActionPerformed
        Ht.getConnect();
        try {
            rs=Ht.sapDiem();
            jTableQLKQHT.removeAll();
            String []inTieuDe = {"Mã sinh viên", "Mã môn", "Điểm thành phần", "Điểm thi", "Điểm trung bình","Thang Điểm 4","Thang điểm chữ","Xếp loại"};
            DefaultTableModel model=new DefaultTableModel(inTieuDe, 0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                model.addRow(v);
            }
            jTableQLKQHT.setModel(model);
        } catch (SQLException e) {
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jbtnSapDiemActionPerformed

    private void jbtnLoadDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoadDiemActionPerformed
        loadKetQuaHocTap();
    }//GEN-LAST:event_jbtnLoadDiemActionPerformed

    private void jbtnThoatDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThoatDiemActionPerformed
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.dispose();
        new QLSV_FORM("chay").setVisible(true);
    }//GEN-LAST:event_jbtnThoatDiemActionPerformed

    private void timkiemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemDiemActionPerformed
        Ht.getConnect();
        try {
            rs=Ht.findDiemByMaSVMaMon(jtxtTimMaSV.getText(), jtxtTimMaMon.getText());
            if(!Ht.checkMaSVMaMon(jtxtTimMaSV.getText(), jtxtTimMaMon.getText())){
                JOptionPane.showMessageDialog(null, "Không tìm thấy mã sinh viên và mã môn");
            }
            jTableQLKQHT.removeAll();
            String []inTieuDe = {"Mã sinh viên", "Mã môn", "Điểm thành phần", "Điểm thi", "Điểm trung bình","Thang Điểm 4","Thang điểm chữ","Xếp loại"};
            DefaultTableModel model=new DefaultTableModel(inTieuDe, 0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                model.addRow(v);
            }
            jTableQLKQHT.setModel(model);
            jtxtTimMaSV.setText("");
            jtxtTimMaMon.setText("");
        } catch (Exception e) {
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_timkiemDiemActionPerformed

    private void tbnTimKiembySvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnTimKiembySvActionPerformed
        Ht.getConnect();
        try {
            rs=Ht.findDiemByMaSV(jtxtTimMaSV.getText());
            if(!Ht.checkMaSV(jtxtTimMaSV.getText())){
                JOptionPane.showMessageDialog(null, "Không tìm thấy mã sinh viên");
            }
            jTableQLKQHT.removeAll();
            String []inTieuDe =  {"Mã sinh viên", "Mã môn", "Điểm thành phần", "Điểm thi", "Điểm trung bình","Thang Điểm 4","Thang điểm chữ","Xếp loại"};
            DefaultTableModel model=new DefaultTableModel(inTieuDe, 0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                model.addRow(v);
            }
            jTableQLKQHT.setModel(model);
            jtxtTimMaSV.setText("");
            jtxtTimMaMon.setText("");
        } catch (Exception e) {
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_tbnTimKiembySvActionPerformed

    private void btnTimKiembyMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiembyMHActionPerformed
        Ht.getConnect();
        try {
            rs=Ht.findDiemByMaMon(jtxtTimMaMon.getText());
            if(!Ht.checkMaMon(jtxtTimMaMon.getText())){
                JOptionPane.showMessageDialog(null, "Không tìm thấy mã môn");
            }
            jTableQLKQHT.removeAll();
            String []inTieuDe =  {"Mã sinh viên", "Mã môn", "Điểm thành phần", "Điểm thi", "Điểm trung bình","Thang Điểm 4","Thang điểm chữ","Xếp loại"};
            DefaultTableModel model=new DefaultTableModel(inTieuDe, 0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                model.addRow(v);
            }
            jTableQLKQHT.setModel(model);
            jtxtTimMaSV.setText("");
            jtxtTimMaMon.setText("");
        } catch (Exception e) {
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnTimKiembyMHActionPerformed
int viTri;private void loadKetQuaHocTap(){
        Ht.getConnect();
        try {
            rs=Ht.GetData("DIEM");
            jTableQLKQHT.removeAll();
            String []inTieuDe = {"Mã sinh viên", "Mã môn", "Điểm thành phần", "Điểm thi", "Điểm trung bình","Thang Điểm 4","Thang điểm chữ","Xếp loại"};
            DefaultTableModel model=new DefaultTableModel(inTieuDe, 0);
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                model.addRow(v);
            }
            jTableQLKQHT.setModel(model);
        } catch (SQLException e) {
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, e);
        }
    }private double thangDiem4(double diemTB){
    if(diemTB>=8.5 && diemTB<=10){
        return 4;
    }
    if(diemTB>=7.7 && diemTB<8.5){
        return 3.5;
    }
    if(diemTB>=7 && diemTB<=7.6){
        return 3;
    }
    if(diemTB>=6.2 && diemTB<=6.9){
        return 2.5;
    }
    if(diemTB>=5.5 && diemTB<=6.1){
        return 2;
    }
    if(diemTB>=4.7 && diemTB<=5.4){
        return 1.5;
    }
     if(diemTB>=4 && diemTB<=4.6){
        return 1;
    }
     if(diemTB<4){
        return 0;
    }
     return 0.0;
}
private String thangDiemChu(double diemTB){
    if(diemTB>=8.5 && diemTB<=10){
       return "A";
    }
    if(diemTB>=7.7 && diemTB<8.5){
        return "B+";
    }
    if(diemTB>=7 && diemTB<=7.6){
        return "B";
    }
    if(diemTB>=6.2 && diemTB<=6.9){
        return "C+";
    }
    if(diemTB>=5.5 && diemTB<=6.1){
        return "C";
    }
    if(diemTB>=4.7 && diemTB<=5.4){
        return "D+";
    }
     if(diemTB>=4 && diemTB<=4.6){
        return "D";
    }
     if(diemTB<4){
        return "F";
    }
     return  "";
}
private String xepLoai(double diemTB){
    if(diemTB>=8.5 && diemTB<=10){
        return "GIỎI";
    }
    if(diemTB>=7 && diemTB<=8.4){
        return "KHÁ";
    }
    if(diemTB>=5.5 && diemTB<=6.9){
        return "TRUNG BÌNH";
    }
     if(diemTB>=4 && diemTB<=5.4){
        return "TB YẾU";
    }
     if(diemTB<4){
        return "KÉM";
    }
     return "";
}

 private void xoaTrangDiem(){
        jtxtMaSV.setText("");
        jtxtMaMon.setText("");
        jtxtDiemTP.setText("");
        jtxtDiemThi.setText("");
        jtxtMaSV.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLyKQHT_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLyKQHT_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLyKQHT_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLyKQHT_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLyKQHT_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiembyMH;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelChon;
    private javax.swing.JPanel jPanelDS;
    private javax.swing.JPanel jPanelNhapDL;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableQLKQHT;
    private javax.swing.JButton jbtnLoadDiem;
    private javax.swing.JButton jbtnSapDiem;
    private javax.swing.JButton jbtnSuaDiem;
    private javax.swing.JButton jbtnThemDiem;
    private javax.swing.JButton jbtnThoatDiem;
    private javax.swing.JButton jbtnXoaDiem;
    private javax.swing.JPanel jpnDiem;
    private javax.swing.JTextField jtxtDiemTP;
    private javax.swing.JTextField jtxtDiemThi;
    private javax.swing.JTextField jtxtMaMon;
    private javax.swing.JTextField jtxtMaSV;
    private javax.swing.JTextField jtxtTimMaMon;
    private javax.swing.JTextField jtxtTimMaSV;
    private javax.swing.JButton tbnTimKiembySv;
    private javax.swing.JButton timkiemDiem;
    // End of variables declaration//GEN-END:variables
}
