/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TranThuyNga
 */
public class QLyLopHoc_form extends javax.swing.JFrame {
public static ResultSet rs=null;
    public Statement st;
    Connection conn = null;
    /**
     * Creates new form QLyLopHoc_form
     */
    public QLyLopHoc_form() {
        new DangNhapForm().setVisible(true);
    }
 public QLyLopHoc_form(String l) {
        initComponents();
        setLocationRelativeTo(null);
        loadDataLH();
        setTitle("Phần mềm quản lý Sinh Viên");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnLop = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtMaLop = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTenLop = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtKhoaHoc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtHeDT = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtMaGVCN = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtMaKhoa = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnThemlop = new javax.swing.JButton();
        btnSualop = new javax.swing.JButton();
        btnsaplop = new javax.swing.JButton();
        btnXoalop = new javax.swing.JButton();
        btnLoadlop = new javax.swing.JButton();
        btnThoatlop = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblop = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txttimkiemlop = new javax.swing.JTextField();
        btnTimKiemlop = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        diem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jpnLop.setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập dữ liệu"));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Mã Lớp");

        txtMaLop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Tên Lớp");

        txtTenLop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Khóa Học");

        txtKhoaHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Hệ Đào Tạo");

        txtHeDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Mã GVCN");

        txtMaGVCN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Mã Khoa");

        txtMaKhoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenLop)
                            .addComponent(txtMaLop)
                            .addComponent(txtKhoaHoc)
                            .addComponent(txtHeDT)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 242, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKhoa)
                            .addComponent(txtMaGVCN))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtHeDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(txtMaGVCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(72, 72, 72))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        btnThemlop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThemlop.setText("Thêm");
        btnThemlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemlopActionPerformed(evt);
            }
        });
        jPanel5.add(btnThemlop);

        btnSualop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSualop.setText("Sửa");
        btnSualop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSualopActionPerformed(evt);
            }
        });
        jPanel5.add(btnSualop);

        btnsaplop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsaplop.setText("Sắp");
        btnsaplop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaplopActionPerformed(evt);
            }
        });
        jPanel5.add(btnsaplop);

        btnXoalop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXoalop.setText("Xóa");
        btnXoalop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoalopActionPerformed(evt);
            }
        });
        jPanel5.add(btnXoalop);

        btnLoadlop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLoadlop.setText("Load");
        btnLoadlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadlopActionPerformed(evt);
            }
        });
        jPanel5.add(btnLoadlop);

        btnThoatlop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoatlop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-1.png"))); // NOI18N
        btnThoatlop.setText("Quay lại");
        btnThoatlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatlopActionPerformed(evt);
            }
        });
        jPanel5.add(btnThoatlop);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách"));

        jtblop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtblop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblop.setPreferredSize(new java.awt.Dimension(400, 400));
        jtblop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblopMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtblop);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("QUẢN LÝ LỚP HỌC");

        txttimkiemlop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnTimKiemlop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimKiemlop.setText("Tìm Kiếm");
        btnTimKiemlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemlopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttimkiemlop, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnTimKiemlop, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiemlop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemlop))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnLopLayout = new javax.swing.GroupLayout(jpnLop);
        jpnLop.setLayout(jpnLopLayout);
        jpnLopLayout.setHorizontalGroup(
            jpnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnLopLayout.setVerticalGroup(
            jpnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLopLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnLopLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PHẦN MỀM QUẢN LÝ SINH VIÊN");

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemActionPerformed(evt);
            }
        });
        jMenuBar1.add(diem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jpnLop, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jpnLop, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemlopActionPerformed
        add();
    }//GEN-LAST:event_btnThemlopActionPerformed

    private void btnSualopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSualopActionPerformed
        update();
    }//GEN-LAST:event_btnSualopActionPerformed

    private void btnsaplopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaplopActionPerformed
        try {
            conn = getConnect();

            ResultSet kq=null;
            Statement st;
            st = conn.createStatement();
            kq=st.executeQuery("select *  from LOP ORDER BY MALOP");

            jtblop.removeAll();
            String []tieuDe={"Mã lớp","Tên lớp","Khóa học","Hệ đào tạo","Mã GVCN","Mã khoa"};
            DefaultTableModel model=new DefaultTableModel(tieuDe,0);
            while(kq.next())
            {
                Vector vector=new Vector();
                vector.add(kq.getString(1));
                vector.add(kq.getString(2));
                vector.add(kq.getString(3));
                vector.add(kq.getString(4));
                vector.add(kq.getString(5));
                vector.add(kq.getString(6));

                model.addRow(vector);
            }
            jtblop.setModel(model);
            clearTextLh();

        } catch (SQLException ex) {
            Logger.getLogger(QLSV_FORM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaplopActionPerformed

    private void btnXoalopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoalopActionPerformed
        delete();

    }//GEN-LAST:event_btnXoalopActionPerformed

    private void btnLoadlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadlopActionPerformed
        loadDataLH();
    }//GEN-LAST:event_btnLoadlopActionPerformed

    private void btnThoatlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatlopActionPerformed
       setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.dispose();
            new QLSV_FORM("chay").setVisible(true);
    }//GEN-LAST:event_btnThoatlopActionPerformed

    private void jtblopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblopMouseClicked
        int row = jtblop.getSelectedRow();
        txtMaLop.setText(jtblop.getValueAt(row, 0).toString());
        txtTenLop.setText(jtblop.getValueAt(row, 1).toString());
        txtKhoaHoc.setText( jtblop.getValueAt(row, 2).toString());
        txtHeDT.setText(jtblop.getValueAt(row, 3).toString());
        txtMaGVCN.setText( jtblop.getValueAt(row, 4).toString());
        txtMaKhoa.setText(jtblop.getValueAt(row, 5).toString());
    }//GEN-LAST:event_jtblopMouseClicked

    private void btnTimKiemlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemlopActionPerformed
        timkiem();
    }//GEN-LAST:event_btnTimKiemlopActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int ref=JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thoát","Thoát",JOptionPane.YES_NO_OPTION);
        if(ref==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void diemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLyLopHoc_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLyLopHoc_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLyLopHoc_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLyLopHoc_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLyLopHoc_form().setVisible(true);
            }
        });
    }
private void clearTextLh() {
        txtMaLop.setText("");
        txtTenLop.setText("");
        txtKhoaHoc.setText("");
        txtHeDT.setText("");
        txtMaGVCN.setText("");
        txtMaKhoa.setText("");
        txttimkiemlop.setText("");
    }
private boolean IsEmpty(){
        if(txtMaLop.getText().equals("")||txtTenLop.getText().equals("")||txtKhoaHoc.getText().equals("")||txtHeDT.getText().equals("")||txtMaGVCN.getText().equals("")||txtMaKhoa.getText().equals("")){
            return true;
        }
        return false;
    }
private boolean MaLopIsEmpty(){
        String sql_id="select count(*) from LOP where MALOP=?";
        try{
            conn=getConnect();
            PreparedStatement pre=conn.prepareStatement(sql_id);
            pre.setString(1, txtMaLop.getText());
            ResultSet re=pre.executeQuery();
            if(re.next()){
                if(re.getInt(1)!=0){
                    return true;
                }
            }
            conn.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Không tồn tại MALOP","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
private void add(){
        if(IsEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Có trường nhập bạn đang để trống","Thông Báo",JOptionPane.ERROR_MESSAGE);
        } 
        else if(!Pattern.matches("[G][V]\\d{3}", txtMaGVCN.getText()))
            JOptionPane.showMessageDialog(rootPane, "Mã Giao viên sai định dạng","Thông Báo",JOptionPane.ERROR_MESSAGE);
        else if(!Pattern.matches("^\\d{4}[-]\\d{4}$", txtKhoaHoc.getText()))
            JOptionPane.showMessageDialog(rootPane, "Khóa học sai định dạng","Thông Báo",JOptionPane.ERROR_MESSAGE);
        else{
            conn=getConnect();
            String SQL="insert into LOP values(?,?,?,?,?,?)";
            try{
                PreparedStatement pre= conn.prepareStatement(SQL);
                pre.setString(1,txtMaLop.getText());
                pre.setString(2,txtTenLop.getText());
                pre.setString(3,txtKhoaHoc.getText());
                
                pre.setString(4,txtHeDT.getText());
               
                pre.setString(5,txtMaGVCN.getText());
                pre.setString(6,txtMaKhoa.getText());
                pre.executeUpdate();
                  loadDataLH();
               clearTextLh();
            } catch (Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu đầu vào không đúng dữ liệu bảng, vui lòng kiểm tra lại","Thông báo",JOptionPane.ERROR_MESSAGE);   
            }
        }   
    }
private void delete(){
        if(MaLopIsEmpty()){
            int res=JOptionPane.showConfirmDialog(rootPane, "Bạn Có muốn xoá không","Xác nhận",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(res==JOptionPane.YES_OPTION){
                 conn=getConnect();
                String SQL="delete from LOP where MALOP=?";
                try{
                    PreparedStatement pre=conn.prepareStatement(SQL);
                    pre.setString(1, txtMaLop.getText());
                    pre.executeUpdate();
                     loadDataLH();
                clearTextLh();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(rootPane, "Xoá không thành công","Thông báo",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Không tồn tại MALOP này trong danh sách","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }
private void update(){
        if(IsEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Có thành phần bạn đang để trống","Thông Báo",JOptionPane.ERROR_MESSAGE);
        }
        else if(!Pattern.matches("[G][V]\\d{3}", txtMaGVCN.getText()))
            JOptionPane.showMessageDialog(rootPane, "Mã Giao viên sai định dạng","Thông Báo",JOptionPane.ERROR_MESSAGE);
        else if(!Pattern.matches("^\\d{4}[-]\\d{4}$", txtKhoaHoc.getText()))
            JOptionPane.showMessageDialog(rootPane, "Khóa học sai định dạng","Thông Báo",JOptionPane.ERROR_MESSAGE);
        else if(MaLopIsEmpty()){
            conn=getConnect();
            String SQL="update LOP set TENLOP=?,KHOAHOC=?,HEDAOTAO=?,MAGVCN=?,MAKHOA=? where MALOP=?";
            try{
                PreparedStatement pre= conn.prepareStatement(SQL);
                pre.setString(6,txtMaLop.getText());
                pre.setString(1,txtTenLop.getText());
                pre.setString(2,txtKhoaHoc.getText());               
                pre.setString(3,txtHeDT.getText());               
                pre.setString(4,txtMaGVCN.getText());
                pre.setString(5,txtMaKhoa.getText());
                pre.executeUpdate();
               loadDataLH();
                clearTextLh();
            } catch (Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu cập nhật lỗi so với dữ liệu bảng, vui lòng kiểm tra lại","Thông báo",JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Không tồn tại MALOP Sách này","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }
 public Connection getConnect() {
        try {
            String url = "jdbc:derby://localhost:1527/QLySV";
            String user = "Nhom10";
            String pass = "123456";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            return DriverManager.getConnection(url, user, pass);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Khong the ket noi voi database \n" + e);
        }
        return null;
    }
     private void loadDataLH() {
         conn=getConnect();
        try{
             String []tieuDe={"Mã lớp","Tên lớp","Khóa học","Hệ đào tạo","Mã Gv","Mã Khoa"};
            DefaultTableModel modelh=new DefaultTableModel(tieuDe,0);
            st= conn.createStatement();
            ResultSet re= st.executeQuery("select * from LOP");
            while(re.next()){
                String MALOP=re.getString("MALOP");
                String TENLOP=re.getString("TENLOP");
                String KHOAHOC=re.getString("KHOAHOC");
                String HEDAOTAO=re.getString("HEDAOTAO");
                String MAGVCN=re.getString("MAGVCN");
                String MAKHOA=re.getString("MAKHOA");
                Vector vt=new Vector();
                vt.add(MALOP);
                vt.add(TENLOP);
                vt.add(KHOAHOC);
                vt.add(HEDAOTAO);
                vt.add(MAGVCN);
                vt.add(MAKHOA);
                modelh.addRow(vt);
            }
             jtblop.setModel(modelh);
            conn.close();
        } catch (Exception ex){
            System.out.println("Error:"+ ex.getMessage());
        }
    }
public void timkiem(){
        conn=getConnect();
        DefaultTableModel modelsach= (DefaultTableModel) jtblop.getModel();
        modelsach.setRowCount(0);
        
        
            if(txttimkiemlop.getText().equals("")){
                JOptionPane.showConfirmDialog(rootPane, "Bạn đang để trống MALOP tìm kiếm","Thông báo",JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE);
                txttimkiemlop.requestFocus();
            }
            else {
                String SQL="select * from LOP where MALOP=?";
                try{
                    PreparedStatement pre=conn.prepareStatement(SQL);
                    pre.setString(1, txttimkiemlop.getText());
                    ResultSet re=pre.executeQuery();
                    while(re.next()){
                        String MALOP=re.getString("MALOP");
                        String TENLOP=re.getString("TENLOP");
                        String KHOAHOC=re.getString("KHOAHOC");
                        String HEDAOTAO=re.getString("HEDAOTAO");
                        String MAGVCN=re.getString("MAGVCN");
                        String MAKHOA=re.getString("MAKHOA");
                        
                        modelsach.addRow(new Object[]{
                            MALOP,TENLOP,KHOAHOC,HEDAOTAO,MAGVCN,MAKHOA
                        });
                    }
                    conn.close();
                    clearTextLh();
                } catch(Exception ex){
                    JOptionPane.showMessageDialog(rootPane, "Dữ liệu không tồn tại","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadlop;
    private javax.swing.JButton btnSualop;
    private javax.swing.JButton btnThemlop;
    private javax.swing.JButton btnThoatlop;
    private javax.swing.JButton btnTimKiemlop;
    private javax.swing.JButton btnXoalop;
    private javax.swing.JButton btnsaplop;
    private javax.swing.JMenu diem;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpnLop;
    private javax.swing.JTable jtblop;
    private javax.swing.JTextField txtHeDT;
    private javax.swing.JTextField txtKhoaHoc;
    private javax.swing.JTextField txtMaGVCN;
    private javax.swing.JTextField txtMaKhoa;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtTenLop;
    private javax.swing.JTextField txttimkiemlop;
    // End of variables declaration//GEN-END:variables
}
